---
- name: Ensure the container user group exists
  group:
    name: "radio-bridge"
    state: present
    gid: "{{ radio_bridge_uid_gid }}"
    system: yes

- name: Ensure the container user exists
  user:
    name: "radio-bridge"
    state: present
    uid: "{{ radio_bridge_uid_gid }}"
    group: "radio-bridge"
    create_home: no
    system: yes
    shell: "/usr/sbin/nologin"

- name: Ensure the docker-compose template directory exists
  file:
    state: directory
    path: "/opt/ansible-docker-compose/radio-bridge"
    mode: 0755

- name: Ensure the Dockerfile and related files are all present
  copy:
    src: "{{ item }}"
    dest: "/opt/ansible-docker-compose/radio-bridge/{{ item }}"
  with_items:
    - Dockerfile
    - Pipfile
    - Pipfile.lock
    - serial_bridge.py

- name: Ensure this service's docker-compose template is present
  template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/radio-bridge/docker-compose.yml
    mode: 0644

- name: Ensure the latest images for the upstream container
  community.docker.docker_image:
    name: "python"
    source: pull
    force_source: yes
    tag: "3.9-alpine"

- name: Ensure the service container(s) is/are started
  docker_compose:
    project_src: /opt/ansible-docker-compose/radio-bridge
    build: yes
